-- MySQL Script generated by MySQL Workbench
-- Wed Jun 18 16:03:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Like` (
  `idLike` INT NOT NULL,
  `Gostou` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLike`),
  CONSTRAINT `IdUsuario`
    FOREIGN KEY (`idLike`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdPublicacao`
    FOREIGN KEY (`idLike`)
    REFERENCES `mydb`.`Publicacao` (`idPublicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publicacao` (
  `idPublicacao` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `Imagem` VARCHAR(45) NOT NULL,
  `Local` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPublicacao`),
  CONSTRAINT `IdUsuario`
    FOREIGN KEY (`idPublicacao`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdPublicacao`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Publicacao` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdComentario`
    FOREIGN KEY (`idPublicacao`)
    REFERENCES `mydb`.`Comentario` (`idComentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdLike`
    FOREIGN KEY (`idPublicacao`)
    REFERENCES `mydb`.`Like` (`idLike`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Imagem` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `DataCriacao` DATE NOT NULL,
  `Ativo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `IdPublicacao`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Publicacao` (`idPublicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdComentario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Comentario` (`idComentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdLike`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Like` (`idLike`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `idComentario` INT NOT NULL,
  `Texto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idComentario`),
  CONSTRAINT `IdUsuario`
    FOREIGN KEY (`idComentario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdPublicacao`
    FOREIGN KEY (`idComentario`)
    REFERENCES `mydb`.`Publicacao` (`idPublicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
